"""
compliance_agent.py
-------------------
Agent responsible for checking if the risk analyst's summary violates
fair lending practices by mentioning protected classes.
"""

import ollama
import json

def run_compliance_agent(risk_summary: str) -> dict:
    """
    Checks a risk summary for compliance violations using Ollama.
    
    Parameters
    ----------
    risk_summary : str
        The summary generated by the risk analyst agent.
        
    Returns
    -------
    dict
        A dictionary with "status" (APPROVED or FLAGGED) and "notes".
    """
    prompt = f"""
    Risk Summary to check: "{risk_summary}"
    
    Task: Check if the text above explicitly mentions any protected demographic classes (gender, marital status, religion, race, or age).
    
    Strict Rules for status:
    - If NO protected classes are mentioned in the summary, status MUST be "APPROVED".
    - If ANY protected classes ARE mentioned in the summary, status MUST be "FLAGGED".
    
    Respond ONLY with a JSON object in this exact format:
    {{
        "status": "APPROVED" or "FLAGGED",
        "notes": "Short explanation of why status was chosen."
    }}
    """
    
    try:
        response = ollama.chat(
            model="llama3.2:1b",
            messages=[
                {
                    "role": "system",
                    "content": "You are a strict fair-lending compliance officer. You must ensure credit decisions are not based on protected demographic classes. You only speak in valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            format="json" # Force JSON output
        )
        
        # Parse the JSON response
        result_str = response["message"]["content"]
        return json.loads(result_str)
        
    except Exception as e:
        return {
            "status": "ERROR",
            "notes": f"Error connecting to Ollama or parsing response. Make sure Ollama is running locally with 'llama3.2:1b'. Details: {e}"
        }
